### ISSUE TITLE
My Results & Thoughts

### ISSUE THREAD

**Issue by roblav96** [xxxzc/themefits#2]
![DVuYzgU](https://i.imgur.com/DVuYzgU.png)

# @xxxzc Not bad my friend!
Maybe tone down the giant `FOLDERS` text up top left :P

**Comment by xxxzc** [comment]
Thank you!
Maybe I should use regular font rather than bold.

**Comment by xxxzc** [comment]
It will looks not clear on my 1080p 15.6’ laptop if I shrink this text.
If you want to tone down this text, here is the steps:
1. use `package control` install [PackageResourceViewer](https://packagecontrol.io/packages/PackageResourceViewer)
2. open quick panel input `Open Resource` then enter
3. input `theme - fits` then enter
4. select 'Fits.sublime-theme', it will open this file
5. search `sidebar_heading`, now you can edit it

Hope this helps :)

**Comment by roblav96** [comment]
@xxxzc I highly recommend picking at https://github.com/ihodev/sublime-boxy source code =]
